on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0

      - run: 'git fetch --force --tags'

      - uses: 'actions/setup-go@v2'
        with:
          go-version: '1.17'

      - name: 'Run GoReleaser'
        uses: 'goreleaser/goreleaser-action@v2'
        with:
          distribution: 'goreleaser'
          version: 'latest'
          args: 'release --rm-dist'
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'

  # TODO: move to goreleaser?
  push-to-docker-registries:
    name: 'Push Docker image to multiple registries'
    runs-on: 'ubuntu-latest'
    permissions:
      packages: 'write'
      contents: 'read'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v2'

      - name: 'Log in to Docker Hub'
        uses: 'docker/login-action@v1'
        with:
          username: '${{secrets.DOCKER_USERNAME}}'
          password: '${{secrets.DOCKER_PASSWORD}}'

      - name: 'Log in to the Container registry'
        uses: 'docker/login-action@v1'
        with:
          registry: 'ghcr.io'
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'

      - name: 'Extract metadata (tags, labels) for Docker'
        id: 'meta'
        uses: 'docker/metadata-action@v3'
        with:
          images: |
            ${{github.repository}}
            ghcr.io/${{github.repository}}
          tags: |
            latest

      - name: 'Build and push Docker images'
        uses: 'docker/build-push-action@v2'
        with:
          context: '.'
          push: true
          tags: '${{steps.meta.outputs.tags}}'
          labels: '${{steps.meta.outputs.labels}}'
