on:
  release:
    types: ['created']

jobs:
  # Credit: https://github.com/benny-discord/cache-server/blob/master/.github/workflows/release.yml
  release-binaries:
    name: 'Release Go Binary'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        goos: ['linux', 'windows', 'darwin']
        goarch: ["386", 'amd64', 'arm64']
    steps:
    - uses: 'actions/checkout@v2'
    - uses: 'wangyoucao577/go-release-action@v1.25'
      with:
        github_token: '${{secrets.GITHUB_TOKEN}}'
        goos: '${{matrix.goos}}'
        goarch: '${{matrix.goarch}}'
        goversion: "https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz"

  push-to-docker-registries:
    name: 'Push Docker image to multiple registries'
    runs-on: 'ubuntu-latest'
    permissions:
      packages: 'write'
      contents: 'read'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v2'

      - name: 'Log in to Docker Hub'
        uses: 'docker/login-action@v1'
        with:
          username: '${{secrets.DOCKER_USERNAME}}'
          password: '${{secrets.DOCKER_PASSWORD}}'

      - name: 'Log in to the Container registry'
        uses: 'docker/login-action@v1'
        with:
          registry: 'ghcr.io'
          username: '${{github.actor}}'
          password: '${{secrets.GITHUB_TOKEN}}'

      - name: 'Extract metadata (tags, labels) for Docker'
        id: 'meta'
        uses: 'docker/metadata-action@v3'
        with:
          images: |
            ${{github.repository}}
            ghcr.io/${{github.repository}}
          tags: |
            latest

      - name: 'Build and push Docker images'
        uses: 'docker/build-push-action@v2'
        with:
          context: '.'
          push: true
          tags: '${{steps.meta.outputs.tags}}'
          labels: '${{steps.meta.outputs.labels}}'
